CREATE TABLE IF NOT EXISTS users (
    ID VARCHAR(45) NOT NULL UNIQUE DEFAULT (SHA1(MD5(UUID()))),
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    role VARCHAR(15) NOT NULL DEFAULT 'customer',
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS user_options (
    ID BIGINT NOT NULL UNIQUE DEFAULT (UUID_SHORT()),
    name VARCHAR(100) NOT NULL,
    value VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (user_id) REFERENCES users (ID)
);

CREATE TABLE IF NOT EXISTS user_sessions (
    ID VARCHAR(45) NOT NULL UNIQUE DEFAULT (SHA1(MD5(UUID()))),
    user_id VARCHAR(255) NOT NULL,
    token VARCHAR(45) NOT NULL DEFAULT (SHA1(MD5(UUID()))),
    expires BIGINT DEFAULT (TIME(NOW() + INTERVAL 1 HOUR)),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (user_id) REFERENCES users (ID)
);

CREATE TABLE IF NOT EXISTS products (
    ID VARCHAR(45) NOT NULL UNIQUE DEFAULT (SHA1(MD5(UUID()))),
    barcode VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (user_id) REFERENCES users (ID)
);

CREATE TABLE IF NOT EXISTS product_options (
    ID BIGINT NOT NULL UNIQUE DEFAULT (UUID_SHORT()),
    name VARCHAR(45) NOT NULL,
    value VARCHAR(255),
    product_id VARCHAR(40) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (product_id) REFERENCES products (ID)
);

CREATE TABLE IF NOT EXISTS product_categories (
    ID BIGINT NOT NULL UNIQUE DEFAULT (UUID_SHORT()),
    name VARCHAR(45) NOT NULL,
    description VARCHAR(500) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS product_brands (
    ID BIGINT NOT NULL UNIQUE DEFAULT (UUID_SHORT()),
    name VARCHAR(45) NOT NULL,
    description VARCHAR(500) NOT NULL,
    image VARCHAR(100),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS product_prices (
    ID VARCHAR(40) NOT NULL UNIQUE DEFAULT (UUID_SHORT()),
    value FLOAT NOT NULL,
    type ENUM('price', 'price_per_pack') NOT NULL DEFAULT 'price',
    product_id VARCHAR(40) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (product_id) REFERENCES products (ID)
);

CREATE TABLE IF NOT EXISTS transactions (
    ID VARCHAR(45) NOT NULL UNIQUE DEFAULT (SHA1(MD5(UUID()))),
    user_id VARCHAR(45) NOT NULL,
    amount_paid FLOAT NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (user_id) REFERENCES users (ID)
);

CREATE TABLE IF NOT EXISTS transaction_items (
    ID BIGINT NOT NULL UNIQUE DEFAULT (UUID_SHORT()),
    transaction_id VARCHAR(40) NOT NULL,
    product_id VARCHAR(45) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    price FLOAT NOT NULL,
    price_type VARCHAR(20) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (transaction_id) REFERENCES transactions (ID),
    FOREIGN KEY (product_id) REFERENCES products (ID)
);